name: Build Java Web App and Deploy
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  checkout_code:
    uses: ./.github/workflows/checkout.yml
  
  Docker_build_push:
    uses: ./.github/workflows/build_images.yml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  
  kubernetes-deploy:
    needs: Docker_build_push
    uses: ./.github/workflows/kubernetes-deploy.yml
    with:
      IMAGE_TAG: ${{needs.Docker_build_push.outputs.IMAGE_TAG_Deploy}}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_NAME: ${{ secrets.ROLE_NAME }}
      APP_NAME: ${{ secrets.APP_NAME }}
      EKS_Cluster_Name: ${{ secrets.EKS_Cluster_Name }}