name: Resubale Workflow Build and Push Docker Images
on: 
  workflow_call:
    secrets:
      secrets:
      AWS_ACCOUNT_ID:
        description: AWS Account ID
        required: true
        
      AWS_REGION:
        description: AWS Region
        required: true
        
      ROLE_NAME:
        description: Role Name
        required: true
        
      APP_NAME:
        description: THe Name of Application
        required: true
        
      ECR_REPOSITORY:
        description: ECR Repository Name
        required: true
    outputs:
      IMAGE_TAG_Deploy:
        description: Image Tag to be deployed
        value: ${{jobs.Build_Push_Docker.outputs.IMAGE_TAG}}
      

jobs:
  Build_Push_Docker:
    outputs:
      IMAGE_TAG: ${{steps.image-tag.outputs.TAG_METADATA}}
      
    runs-on: eks_runner
    steps:
      # Checkout Code
      - name: Get code
        uses: actions/checkout@v4
      # AWS Authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{secrets.AWS_REGION}}
  
      # Login in Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Building Docker Context
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders      
      
      # Docker Image MetaData    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{steps.login-ecr.outputs.registry}}/${{secrets.ECR_REPOSITORY}}
          tags: |
            type=semver,pattern={{version}}
      
      - name: Set Image Tag
        id: image-tag
        run: echo "TAG_METADATA=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}" >> $GITHUB_OUTPUT
      
      # Build, tag, and push docker image to Amazon ECR
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{secrets.APP_NAME}}/
          file: ${{secrets.APP_NAME}}/Dockerfile 
          push: true
          tags: ${{ steps.meta.outputs.tags }}