name: Workflow for kubernetes deploy
on: 
  workflow_call:
    inputs:
      IMAGE_TAG:
        description: Docker Image tag
        required: true
        type: string

    secrets:
      AWS_ACCOUNT_ID:
        description: AWS Account ID
        required: true
        
      AWS_REGION:
        description: AWS Target Region
        required: true
        
      ROLE_NAME:
        description: Role Name
        required: true

      APP_NAME:
        description: THe Name of Application
        required: true
        
      EKS_Cluster_Name:
        description: Target EKS Cluster Name
        required: true

jobs:
  K8s_EKS_Deploy:
    runs-on: eks_runner
    steps:
      - name: Get code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Update kubeconfig
        run: |
          sudo apt install unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip

          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          
          sudo ./aws/install
          aws eks update-kubeconfig --name ${{ secrets.EKS_Cluster_Name }} --region ${{ secrets.AWS_REGION }}
    
      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

          sed -i.bak "s/IMAGE_TAG/$IMAGE_TAG/g" Helm_Chart/${{secrets.APP_NAME}}/values.yaml
          helm upgrade --install ${{secrets.APP_NAME}} \
          --namespace ${{secrets.APP_NAME}} \
          --create-namespace \
          ./Helm_Chart/${{secrets.APP_NAME}}